### ISSUE TITLE
Global database connection seems to be not used by models.

### ISSUE THREAD

**Issue by katyukha** [rikkimax/Dvorm#3]
I have tryed to use this project separate from Cmsed and to configure global database connection via _dvorm.databaseConnection(dbSettings)_ to use mongo. But it seems that models still use Memory datbase type, not Mongo.

So as I think model's _databaseConnection()_ method should return Model's connection if there are some and if there no one model-specific connection then return global connection.

**Comment by Munrek** [comment]
Seems to be working, but I am currently fighting with other problems, stay tuned.
